services:
  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/wordpress
    restart: always

  mariadb:
    container_name: mariadb
    env_file: .env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 5
    expose:
      - "3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    env_file: .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - "9000"
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/wordpress
    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /root/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /root/data/mariadb

networks:
  inception:
      driver: bridge
